# Generated by Django 4.2.9 on 2024-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
