# Generated by Django 4.2.9 on 2024-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_procedure_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='file/images/'),
        ),
    ]
