# Generated by Django 4.2.9 on 2024-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_doctor_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
